### ISSUE TITLE
Support strings for JSON RPC id attribute

### ISSUE THREAD

**Issue by esocode** [INFURA/infura#102]
The Infura JSON RPC API currently only supports numeric (integer) IDs for the `id` attribute of RPC request and returns a 400 when using strings.The JSON RPC specification explicitly allows number or string values and both geth and parity implement that accordingly. This could cause confusion for developers that want to migrate their code to use the Infura backend.

**Comment by hewigovens** [comment]
Some additional informations:

1. Quote from https://www.jsonrpc.org/specification

> id An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2]

2. You can't use infura with MyCrypto since MyCrypto uses hex string for id (code is here: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/nodes/rpc/client.ts#L13)

**Comment by esocode** [comment]
Yes, works now. I'm closing this Issue.
