### ISSUE TITLE
Ropsten out of sync?

### ISSUE THREAD

**Issue by joaomacp** [INFURA/infura#112]
web3.eth.getBlock('latest') is returning erratically: sometimes it returns 954056, other times 3377682 (which seems more correct)...

I think this was working fine before (up to yesterday). Is there any other way of getting INFURA's latest block number?

Happening on https://ropsten.infura.io

EDIT: 5 minutes later, it seems to be OK again.

**Comment by tueric** [comment]
There seems to be issues on Ropsten in general right now. https://github.com/ethereum/go-ethereum/issues/16884
