### ISSUE TITLE
Infura is (currently) really slow.

### ISSUE THREAD

**Issue by gburtini** [INFURA/infura#121]
We have noticed in the last 48 hours huge amounts of latency on the infura nodes we're reaching. For example, we're seeing between 300ms and 1000ms time-to-first-byte (note, the rest of the response takes approximately 2ms; very fast).

Is there a status page or somewhere we can evaluate the load?  This status page: https://infura.io/status reports average load times, showing 350ms currently, but it does not have any sort of history. According to the green indicator on the page, this is considered normal.

**Comment by egalano** [comment]
Thanks for reporting. Our monitoring isn’t seeing an increase in latency on our edge network. Are you seeing this delay on all rpc requests or only certain methods? Also from what geographical region are your requests coming from?

**Comment by jamatulli** [comment]
@gburtini has this situation improved for you or are you still seeing issues with latency?

**Comment by gburtini** [comment]
We're back down to consistently less than 100ms now. 

To answer your questions, it appeared to be pretty consistently high latency across all requests; we're located on the west coast, but appear to be hitting ELB at us-east-1 when reaching mainnet.infura.io.
