### ISSUE TITLE
Infura does not folllow JSON-RPC properly; returning HTTP 405 errors instead of JSON-RPC error objects

### ISSUE THREAD

**Issue by Qqwy** [INFURA/infura#124]
This issue is probably related to [this MetaMask issue](https://github.com/MetaMask/metamask-extension/issues/4693)

When the INFURA API is called using the JSON-RPC pathway with a method that does not exist, it will not respond using the format indicated in the JSON-RPC standard ([link](https://www.jsonrpc.org/specification#error_object)) but instead return an HTTP status code 405 with an empty response body.

Common JSON-RPC clients, including the client that MetaMask use, will map this error to an 'internal JSON-RPC error', rather than an 'Method does not exist or is not available' error.

### Example call:

```
curl --verbose -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "id": 1, "method": "web3_sha4", "params": ["0x10"]}' "https://mainnet.infura.io/YOUR_API_KEY"
```

### Expected response:

```
{
  "id": 1,
  "error": {
    "code": -32601,
    "message": "JSON-RPC method not found"
  }
}
```

### Actual response:

```
```
_(0 bytes; with an HTTP status code 405)_

**Comment by ryanschneider** [comment]
This has been changed, we now return proper JSONRPC responses, relevant curl output snippet:

```
< HTTP/2 400
< date: Thu, 06 Dec 2018 01:05:11 GMT
< content-type: application/json
< content-length: 113
< vary: Origin
<
* Connection #0 to host mainnet.infura.io left intact
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"The method web3_sha4 does not exist/is not available"}}
```

**Comment by Qqwy** [comment]
Awesome! Thank you :slightly_smiling_face:
