### ISSUE TITLE
IPFS: No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by mallendeo** [INFURA/infura#131]
I'm getting this cors error when using `ipfs.object.patch.addLink`

> Failed to load https://ipfs.infura.io:5001/api/v0/object/patch/add-link?arg=QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn&arg=test.jpg&arg=QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR&stream-channels=true: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Example using fetch:
```js
const HOST = 'https://ipfs.infura.io:5001/api/v0'
const dir = 'QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn'
const file = 'QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR'

fetch(
  `${HOST}/object/patch/add-link?arg=${dir}&arg=test.jpg&arg=${file}&stream-channels=true`,
  { method: 'POST' }
)
```

**Comment by ncocchiaro** [comment]
With the latest deployment the CORS issues should be resolved, however you'll still get an error when trying to use the `/object/patch` RPCs as they are not in the subset of the IPFS API that we currently expose. We recently published new documentation at https://infura.io/docs/ with all supported endpoints.
