### ISSUE TITLE
Call error 11: Deadline exceeded (timeout)

### ISSUE THREAD

**Issue by wighawag** [INFURA/infura#14]
I got at least one instance of : ,Call error 11: Deadline exceeded (timeout)

What does it mean ?

**Comment by maurycyp** [comment]
@wighawag Could you provide more information or clarify what you mean? Otherwise, I will have to close this issue.

**Comment by wighawag** [comment]
Sorry, I do not recall having more info than that.
I ll reopen if it happens again

Thanks
