### ISSUE TITLE
Gateway Time-out when pinning IPFS entries

### ISSUE THREAD

**Issue by luisivan** [INFURA/infura#15]
How to replicate:

`curl "https://ipfs.infura.io:5001/api/v0/pin/add?arg=QmTr9QeD3Fr7apJD2ogd1q7NKmmv2KBL5KFP19gSEJz3g5&recursive=true"` (with an IPFS object)

`curl "https://ipfs.infura.io:5001/api/v0/pin/add?arg=QmRfkxM6b9Gd8dNzkJXdNSwxCQQDTJAdCnyNXjBGnhWue3&recursive=true"` (with IPNS)

Both timeout, would love some help in figuring out how to resolve it! :)

**Comment by egalano** [comment]
Thanks for filing the issue Luis I will try to reproduce. Can you show me your full curl query with headers, method, etc with `-vvv` output?

**Comment by luisivan** [comment]
Sure! Here it goes:

```
~ B⃦ ~> curl "https://ipfs.infura.io:5001/api/v0/pin/add?arg=QmRfkxM6b9Gd8dNzkJXdNSwxCQQDTJAdCnyNXjBGnhWue3&recursive=true" -vvv
*   Trying 34.192.181.130...
* TCP_NODELAY set
* Connected to ipfs.infura.io (34.192.181.130) port 5001 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: ipfs.infura.io
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /api/v0/pin/add?arg=QmRfkxM6b9Gd8dNzkJXdNSwxCQQDTJAdCnyNXjBGnhWue3&recursive=true HTTP/1.1
> Host: ipfs.infura.io:5001
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 504 Gateway Time-out
< Server: nginx/1.10.0 (Ubuntu)
< Date: Fri, 31 Mar 2017 13:13:39 GMT
< Content-Type: text/html
< Content-Length: 192
< Connection: keep-alive
<
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host ipfs.infura.io left intact
```

**Comment by egalano** [comment]
We have significantly improved and scaled up our IPFS servers in the last few months. Closing this issue for now. Please reopen if this is still an issue for you.

**Comment by ligi** [comment]
@egalano  should I open another issue for this or can we reopen this one?

**Comment by egalano** [comment]
We can reopen this one. @ligi I think it might be related to this IPFS issue: https://github.com/ipfs/go-ipfs/issues/4122

On a local IPFS node (not using Infura) I was also unable to pin `QmT9P4zKLFYBPTbP7wYUHCW2AzhBcwvoxSAwRJdbQLXT9E`

**Comment by 5310** [comment]
Can we get an update on this please? 

I tried to pin the following hash (a static site with eight files totaling 45kB,) with the API, but it timed out as well. (A simple 66B text file did pin just fine.)

The upstream issue ipfs/go-ipfs#4122 was supposedly fixed in December, slated to release with IPFS 0.4.14 which only just hit release-candidate, but I myself had no issue pinning that hash remotely on an IPFS node running the "stable" version 0.4.13 from November.

It seems like the Infura IPFS node is still running 0.4.11 from back in September. Can it be possible to update to 0.4.13 and try again?

My test hash is: `QmeQjmhhyN9cVNEeVzN85o8VuFtxVAKk4NN6xraiMGKwHU`
It is now pinned by [eternum.io](https://www.eternum.io/ipfs/QmeQjmhhyN9cVNEeVzN85o8VuFtxVAKk4NN6xraiMGKwHU/) so it can be pinned elsewhere even when I'm offline:

**Comment by ncocchiaro** [comment]
We're in the process of pushing a number of updates to our IPFS nodes and an upgraded version of go-ipfs will be part of that. I'll update this issue as soon as this is done.

**Comment by ncocchiaro** [comment]
Thanks for your patience. We hit a small snag with the upgrade but should be able to move forward with it tomorrow.

**Comment by ncocchiaro** [comment]
We've updated to 0.4.13 and I was able to pin the hash you provided successfully. We'll do more testing on 0.4.14, which was just released, before we update to that version.

**Comment by 5310** [comment]
Hurray! It's working. 

I also upgraded to 0.4.14 today and turned on the new pubsub feature. Everything's working fine so far, and hopefully that sticks. 

Looking forward to the authenticated API extensions from INFURA :]

**Comment by ncocchiaro** [comment]
We're now on 0.4.14 and aren't seeing problems. I'm going to close this issue for now, and we can open a new one if anything else comes up.

**Comment by chisNaN** [comment]
Hello I am unable to reach (recently) my ipfs content added thru a infura node created on the dashboard.
Returning error gateway timeout
Data are photo quite low quality.
I hope to retrieve these pictures one day (((
Regards

**Comment by EnchanterIO** [comment]
Hey @chisNaN, we will look into the issue. Please visit https://support.metamask.io/develop and open a support ticket using the widget in the bottom right corner. Choose: Metamask Support -> Infura -> Service Access Request -> IPFS:

Make sure to include your `project id` and the `cid` which is returning you the gateway timeout error.

![Image](https://github.com/user-attachments/assets/056c98d0-2626-4d27-9716-4b0ffab4011e)

**Comment by chisNaN** [comment]
Hello thanks for your help.
Done
regards
