### ISSUE TITLE
CORS headers issue - Infura does not work on Safari and iOS

### ISSUE THREAD

**Issue by bladeSk** [INFURA/infura#156]
Infura does not work on Safari (both Mac and iOS versions), as Safari does not support wildcards in CORS headers and refuses to connect with the following error:

> Failed to load resource: Origin https://example.com is not allowed by Access-Control-Allow-Origin

In order to fix this, you need to replace this header `access-control-allow-origin: *` with an explicit URI - ie. `Access-Control-Allow-Origin: https://example.com`.

[According to Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), the best practice is to take the `Origin` from request headers and copy it to the response's `Access-Control-Allow-Origin` header instead of using a wildcard.

Chrome and Firefox work fine with the current headers.

**Comment by idpsycho** [comment]
Seems like there is a workaround for web3: https://github.com/ethereum/web3.js/issues/1802
Although the infura headers should probably be configured as suggested, explicitly stating host, it's a common issue.

**Comment by jamesmorgan** [comment]
The work around isn't ideal especially since a lot of projects will start to update to truffle 5 which now brings in the latest web3. Any ideas on alternatives to fixing this solutions other than the suggested downgrading of web3?

**Comment by micahriggan** [comment]
@maurycyp  @johanherman who would we talk to about getting Infura's CORS headers to use the Origin that made the request?

This is currently breaking web3 applications on IOS and Safari

**Comment by ryanschneider** [comment]
This issue should now be resolved.
