### ISSUE TITLE
401 when calling a contract's function

### ISSUE THREAD

**Issue by dgaviola** [INFURA/infura#159]
I'm trying to execute a function in a test contract:

```
curl -X POST \
  https://ropsten.infura.io/v3/api-key/eth_call \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: de6e8143-53c2-ae67-7523-a023adfea4eb' \
  -d '{"id":1542118207867,"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xb0c55094816978a74bd972a03e84894d6787b4a6","data":"0x17d7de7c"},"latest"]}'
```

However I'm getting a 401 error. I tried adding the contract in Infura's dashboard, but that didn't help. Also tried to use basic HTTP auth with the API key and secret, but didn't work either.

**Comment by dgaviola** [comment]
I just removed the `v3` in the URL and it started to work. I think it is a bit confusing that the dashboards gives you a URL that does not work and the docs points you to a different URL.

**Comment by dgaviola** [comment]
After more debugging, it seems like my problem was a trailing `/` in the URL. Removing it fixed the issue, even when using `v3`.

**Comment by ryanschneider** [comment]
Sorry for the confusion, we are actively updating the documentation to make v3 usage more clear, we hope for the changes to go live soon.

As you found, it was the trailing slash that caused the issue, I'll see if we can support that, or at least provide a better error message.
