### ISSUE TITLE
Should return `method not found` JSON RPC response instead of HTTP 405.

### ISSUE THREAD

**Issue by MicahZoltu** [INFURA/infura#16]
Per the [JSON-RPC specification](http://www.jsonrpc.org/specification#error_object), unsupported methods should return a JSON-RPC response (presumably HTTP 200) with details
> code: -32601;  message: "Method not found"

`curl https://ropsten.infura.io/ -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_subscribe","params":["newHeads"],"id": 1}' -v` shows that Infura is responding with an HTTP `405 Method Not Allowed` with no body.

Parity and Geth both respond with `HTTP 200` and a JSON-RPC error `Method not found`, so Infura behaving differently causes clients that are expecting a protocol error to potentially misbehave when they receive a transport error.

**Comment by egalano** [comment]
Thanks for reporting this @MicahZoltu and apologies for the late response. @maurycyp do you have any objections to this change?

**Comment by ryanschneider** [comment]
Fixed alongside #124.
