### ISSUE TITLE
Error (429) when  adding file via IPFS RPC gateway

### ISSUE THREAD

**Issue by pwrstudio** [INFURA/infura#163]
I am using the infura IPFS node to add files.

I connect from a node app using:

`const ipfs = ipfsAPI({host: 'ipfs.infura.io', port: '5001', protocol: 'https'})`

And then:

```
      ipfs
        .add(Buffer.from(text))
        …
```
This was working well up until recently (or possibly not so recently – it is a for a side project so I have not looked at it for about 6 months...)

Now, this results in the following error:

`Error: Server responded with 429`

This should mean "too many requests", but I am not making **that** many requests – less than 100. And the error seems to appear already for the first request I send.

Any Idea what as changed to cause this (my code has not)?

I thought that maybe authentication was obligatory now, but cant find any information that this is so for IPFS.

**Comment by fedorinoGore** [comment]
Same error...
@pwrstudio Any insights?

**Comment by pwrstudio** [comment]
@fedorinoGore 
I actually switched over to [ipfsnode.de](ipfsnode.de) to add files.
Would love to know if this is a functionality that infura has disabled, or if we are just missing something here...

**Comment by pwrstudio** [comment]
Closing this as adding files works again. Not sure if the problem was on my end.

**Comment by bigchiano** [comment]
> Closing this as adding files works again. Not sure if the problem was on my end.

It's a rate-limiting error, I am running into the same error trying to upload in bulk. 

Is ipfsnode.de a thing? the link seems to be broken.
