### ISSUE TITLE
The method eth_newBlockFilter does not exist/is not available

### ISSUE THREAD

**Issue by yang24201** [INFURA/infura#173]
I'm using infura with web3j in my project. I want to subscribe the transaction and my code like this:
```
web3j.transactionFlowable().subscribe(tx -> {
        log.info("receive new transaction: " + tx.getTo());
}, e -> {
        log.error("monitor eth transaction error: " + e.getMessage());
});
```
An error occurs saying 
`Invalid request: The method eth_newBlockFilter does not exist/is not available`

But I can find eth_newBlockFilter method in infura doc:
https://infura.io/docs/ethereum/wss/eth_newBlockFilter

How can I subscribe the transaction? Anything wrong with my code ?

My web3j version is 4.1.1

**Comment by ryanschneider** [comment]
Subscriptions and filters are only available over websocket connections, so make sure you are connecting via websocket and not https.

https://infura.io/docs/ethereum/wss/introduction
