### ISSUE TITLE
ipfs says CORS is not allowed?

### ISSUE THREAD

**Issue by hrishikeshio** [INFURA/infura#2]
XMLHttpRequest cannot load http://ipfs.infura.io:5001/api/v0/add?stream-channels=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 400.

This makes the service useless. Am I missing something?

**Comment by OR13** [comment]
+1 bump

perhaps an example with http-server exists somewhere?

**Comment by hermanjunge** [comment]
You may need to point to `https`

**Comment by OR13** [comment]
thanks @hermanjunge, using `IpfsApi(host, port, {protocol: 'https'})` resolved my issue.

**Comment by FedericoCapello** [comment]
I'm currently testing this sample app https://github.com/ipfs/js-ipfs-api/tree/master/examples/name-api and I would like to use the INFURA ipfs node, however, when I change this line:

`const ipfs = window.IpfsApi('/ip4/127.0.0.1/tcp/5001')`

to this line:

`const ipfs = window.IpfsApi('ipfs.infura.io', '5001', {protocol: 'https'})`

and try to publish a file it gives me first a warning:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ipfs.infura.io:5001/api/v0/name/publish?arg=QmZbj5ruYneZb8FuR9wnLqJCpCXMQudhSdWhdhp5U1oPWJ&stream-channels=true. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

and then an error:

> Error: XHR error
Stack trace:
IpfsApi</</ClientRequest.prototype._onFinish/xhr.onerror@https://unpkg.com/ipfs-api@17.2.4/dist/index.js:30117:23

How can I make it work with INFURA? Thanks
