### ISSUE TITLE
cannot access ipfs infura

### ISSUE THREAD

**Issue by niktrix** [INFURA/infura#20]
adding file to ipfs infura gives timeout

curl -F "file=dasd.png" "https://ipfs.infura.io:5001/api/v0/add"

curl: (28) Connection timed out after 300998 milliseconds

**Comment by egalano** [comment]
Thanks for the bug report @niktrix I'll take a look at this

**Comment by egalano** [comment]
@niktrix you are missing an `@` It should be
`curl -F "file=@dasd.png" "https://ipfs.infura.io:5001/api/v0/add"`

Please re-open this issue if it still does not work for you.
