### ISSUE TITLE
Create ropsten account

### ISSUE THREAD

**Issue by RamiroMoreira** [INFURA/infura#21]
Hello, i'm having an issue, i think is easy to solve but i don't know how. I'm using infura and trying to use the ropsten test net. But i don't have a ropsten account so i can't make a transaction. Someone can tell me how to create an account?

**Comment by maurycyp** [comment]
@RamiroMoreira You can use something like Metamask ( https://metamask.io/ ) to create and manage accounts.  They even give you 1 Ropsten ether to get started.  Check out their videos and documentation and you should be good to go.
