### ISSUE TITLE
not allowed - transfer quota reached: 403 (Forbidden) Error when using Infura IPFS gateway

### ISSUE THREAD

**Issue by naftalimurgor** [INFURA/infura#224]
I'm running into issues while trying to use IPFS gateway on infura
Desired behavior:
```javascript
  try {
      const ipfs = create({
      url: "https://ipfs.infura.io:5001/api/v0",
      headers: { Authorization: authorization }
    });
    return ipfs
  } catch (err) {
    console.error(`Failed to connect to IPFS with:`, err)
  }
```

**Comment by EnchanterIO** [comment]
Hi! Seems like you exceeded your quotas?

Check your project settings and review if you have any hardlimits configured:
![Screenshot 2022-07-11 at 12 10 56](https://user-images.githubusercontent.com/3595242/178241881-6c965de7-6160-4e70-9939-0de1b7b395e0.png)

**Comment by naftalimurgor** [comment]
Hello @EnchanterIO 
Thanks a bunch, that resolved the issue. Again, thanks.
