### ISSUE TITLE
IPFS Send file from browser

### ISSUE THREAD

**Issue by bkawk** [INFURA/infura#23]
Is there any documentation for how and where to send a file to IPFS? 

Do I simply make a POST to this address `https://ipfs.infura.io:5001/api/v0/add` and post the image as base64 or an array buffer?

**Comment by critesjosh** [comment]
you can use the ipfs-api node package:

https://www.npmjs.com/package/ipfs-api

`var ipfsAPI = require('ipfs-api')
 
// connect to ipfs daemon API server
var ipfs = ipfsAPI('ipfs.infura.io', '5001', {protocol: 'https'}) 

        var fileReader = new FileReader()
        fileReader.readAsArrayBuffer(file)

        fileReader.onload = function(){
          var data = fileReader.result
          var buffer = Buffer.from(data)
          var content = []
          content.push({
            path: filepath,
            content: buffer
          })

          ipfs.files.add(content, (err, res) => {
              console.log(err, res)
          })
`

**Comment by johanherman** [comment]
Hey @bkawk. This is an old issue, but I hope the help you received previously was enough for you to get going. Don't hesitate otherwise to ask again if you need any clarifications or other pointers.
