### ISSUE TITLE
Two possible Infura issues

### ISSUE THREAD

**Issue by Manidos** [INFURA/infura#24]
Hey! I'm using `ethers.js` library to connect to the Ropsten network. 
I have two issues that might have someting to do with your awesome gateway.
The issues started today.

First issue — [getBalance is unreliable in production](https://github.com/ethers-io/ethers.js/issues/31)
Second issue —[Each new block triggers all past events](https://github.com/ethers-io/ethers.js/issues/32)

If you think it does have something to do with what's going on under your hood, please check it out. 
If you need any aditional info I'm happy to provide!

**Comment by egalano** [comment]
Thanks for reporting and providing code samples.  We'll investigate and try to reproduce.

**Comment by Manidos** [comment]
@egalano No problem, that's the least I can do. 
Anyway, I want to inform you that the problems are gone now. It's been 30 minutes or so since everything went back to normal. Thank you for the great work!

**Comment by egalano** [comment]
Thanks for verifying @Manidos . We did find that one of our cluster nodes was out of sync and we were able to correct that and are working on our monitoring to catch this in the future.
