### ISSUE TITLE
Transactions sent using sendRawTransaction not working

### ISSUE THREAD

**Issue by Joeblockmark** [INFURA/infura#25]
I am trying to send a transaction using eth_sendRawTransaction using the following code:
`HTTP.call('POST',node,{data:{"jsonrpc":"2.0","id":1,"method":"eth_sendRawTransaction","params":['0xabc123...']},headers: {'Content-Type': 'application/json'}})`

 I get the following response which seems to suggest that it has worked, however when I look at it on a blockchain explorer such as etherscan, [nothing shows up.](https://etherscan.io/tx/0x81dbf2da93aac87e61cd4e577943faf5885338b6dbc039fbb6f6724122dbe103)

`{ statusCode: 200,
  content: '{"jsonrpc":"2.0","id":1,"result":"0x81dbf2da93aac87e61cd4e577943faf5885338b6dbc039fbb6f6724122dbe103"}\n',
  headers: 
   { date: 'Wed, 19 Jul 2017 16:02:27 GMT',
     'content-type': 'application/json',
     'content-length': '103',
     connection: 'close',
     server: 'nginx/1.10.3 (Ubuntu)',
     vary: 'Origin' },
  data: 
   { jsonrpc: '2.0',
     id: 1,
     result: '0x81dbf2da93aac87e61cd4e577943faf5885338b6dbc039fbb6f6724122dbe103' } }`

Is this what a successful deployment should look like?

**Comment by tueric** [comment]
@Joeblockmark can you provide us with some more information with respect to the payload? Namely the network you used, what url you send the request to, gasPrice, etc... Thanks

**Comment by tueric** [comment]
@Joeblockmark Hey your gasPrice is only 100... You need a much larger gasPrice. Recommended on mainnet is 21Gwei.
