### ISSUE TITLE
Please provide PHP example for eth_sendRawTransaction

### ISSUE THREAD

**Issue by ftppro** [INFURA/infura#33]
I wish to have a PHP script use Infura's endpoint to call eth_sendRawTransaction. I have a PHP script which uses curl to call functions through Infura's endpoint, like eth_getBalance.

I use BlockCypher's "signer" program to sign data at BlockCypher.

The following description of eth_sendRawTransaction does not indicate how to create the signed transaction data:
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendrawtransaction

Please provide a snippet of PHP code which exemplifies how to create the signed transaction data. At the place where the data needs to be signed, just use this line of code:
$sSignature = exec("./signer $sToSign $sPrivateKey");

I'm sure many other people will benefit from this example.

**Comment by egalano** [comment]
Apologies for the late response @ftppro we don't have a dedicated support team yet but are working on getting a proper support pipeline in place. I'm not aware of a PHP library that supports offline transaction signing like in the libraries that exist for Javascript and Python. If you have found one please share it here for others.

I am not a PHP programmer but this is [a great write up on the internals of an ethereum transaction](https://medium.com/@codetractio/inside-an-ethereum-transaction-fa94ffca912f) . You can use that as a basis to understand how to do tx signing in PHP. You will need to understand the `sign` method as implemented in the [ethereumjs-tx lib](https://github.com/ethereumjs/ethereumjs-tx/blob/master/index.js#L231)

**Comment by Schiocco** [comment]
I want it too
