### ISSUE TITLE
Please add `ethaud` currency pair to support getting rates for Australian Dollar (AUD)

### ISSUE THREAD

**Issue by strelok1** [INFURA/infura#34]
Metamask is switching to Infura currency API which does not have support for AUD yet. There are many blockchain enthusiasts in Australia and it would be great to have the balances displayed in AUD.

https://github.com/MetaMask/metamask-extension/pull/2177

**Comment by maurycyp** [comment]
Thank you @strelok1 , I will add the ethaud pair and update this ticket when the task is complete.

**Comment by maurycyp** [comment]
Completed.

https://api.infura.io/v1/ticker/ethaud
