### ISSUE TITLE
Description of “Ferryman” Service Layer architecture

### ISSUE THREAD

**Issue by litvintech** [INFURA/infura#36]
Please, provide description of Ferryman Service Layer architecture and proxy load balance + Redis/SQL
1. What instruments are you using and how are you using them?
2. Why don't you opensourced service layer?

**Comment by litvintech** [comment]
@wuehler @maurycyp may you guys please answer my question?

**Comment by litvintech** [comment]
@mbgodsey are you going to opensource ferryman?

**Comment by mbgodsey** [comment]
We have no plans to open source Ferryman at this time.  We will announce if those plans change.

**Comment by tjayrush** [comment]
You should push the caching layers out to the clients, the requesters. They should be caching, not you.

**Comment by listenaddress** [comment]
Hey @egalano! I'm curious, what are your new caching mechanisms and why you were thinking of using SQL and Redis less?
