### ISSUE TITLE
Best practice for making multiple consecutive requests?

### ISSUE THREAD

**Issue by doraemondrian** [INFURA/infura#38]
Hi I'm trying to migrate my existing Dapp I've been testing on testrpc onto Infura, and have come across a couple of questions I hadn't thought of before. Basically I'm trying to:

1. Query a list of all tokens
2. For each token query more metadata
3. Fill out an entire list on the view using the above two results

As far as I know Solidity doesn't support complex object as a return value so I've been doing it this way, and this has been working fine when I'm using my own node or testrpc since each request is basically like a local fetch.

However when it comes to Infura, I have to make multiple POST request to the API endpoint, and I'm not sure if this is the desired usage of the platform.

Is there a recommended way to deal with this type of situation? (Maybe batch request?) Otherwise I will always be making multiple requests just to draw a single table.

**Comment by egalano** [comment]
Thanks for checking in with us @doraemondrian . Unfortunately this is a limitation of the current Ethereum JSON RPC API. If there were a more efficient method for querying token data, it wouldn't require as many HTTP requests. The best thing you can do as a client developer is to make use of client-side caching to not pull redundant data too often and also to avoid polling for token balance information more often than once per block. We often see people building dapps that query for balance changes several times a second which really doesn't make sense in a blockchain world where the unit of time is only as granular as the most recent block.

Whether you are building this with the intention of using Infura, or if you are expecting all users to be running their own node these are still the best practices to adhere to to ensure a good Dapp user experience.

If you would be interested in a separate more efficient token metadata/balance API independent of the Ethereum JSON RPC API, please create a separate issue and our team will consider implementing it as a feature if enough users find value in it.
