### ISSUE TITLE
web3.eth.filter and subsequent get exits immediately

### ISSUE THREAD

**Issue by mrwillis** [INFURA/infura#39]
Hi,

Environment: 
`"web3": "0.19.0"`
`node`: `8.9`

Trying to figure out what is going on here. I am using `"web3": "0.19.0"` and trying to call some `eth_getLogs` through `web3`. Going through `curl` there are no issues with the infura mainnet but in `web3` it looks like there is something wrong and I can't quite figure it out. Here is my simple code trying to get events from block 3000000 to 3000500 for the golem contract

```javascript
web3 = new Web3(new Web3.providers.HttpProvider('https://mainnet.infura.io/MYTOKEN'))
// web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'))

const gntAddress = '0xa74476443119A942dE498590Fe1f2454d7D4aC0d'
const transactions = []
const startBlock = 3000000
const endBlock = 3000500

const filter = web3.eth.filter({
  fromBlock: startBlock, toBlock: endBlock, address: [gntAddress], topics: []
})
filter.get((error, logs) => {
// do stuff
}
```

The process just exits immediately with no error. If I substitute for my own node `localhost:8545` there are no issues (apart from being really slow :P)

Any ideas?

Thanks

**Comment by chuacw** [comment]
Infura does not support event filters.

**Comment by egalano** [comment]
@mrwillis You can't subscribe to events via Infura using the JSON RPC newFilter method which is what that library uses under the hood. You can use the web3 ZeroClient provider which works around that by tracking filters on the client side. https://github.com/MetaMask/provider-engine/blob/master/zero.js
Example here https://github.com/INFURA/infura/issues/10#issuecomment-303878754

**Comment by egalano** [comment]
Closing. Please re-open if you are still having issues.
