### ISSUE TITLE
API Help

### ISSUE THREAD

**Issue by morphers82** [INFURA/infura#40]
I for the life of me can't get the api call to work.
I send a GET request to https://api.infura.io/v1/jsonrpc/mainnet/eth_getBlockByNumber
using application/json for content-type and accept
and i try to fill in the params value but thats where i have no idea what to put in it.
I am using Postman and try something like key: params value: [4000000]  where the BlockNumber =4000000  and i just get this as reponse:
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32602,
        "message": "missing value for required argument 0"
    }
}

what am I doing wrong, what do I need to do to make this work

**Comment by comodoro** [comment]
getBlockByNumber has two parameters, see
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber

Dne 5. 12. 2017 12:07 dopoledne napsal uživatel "morphers82" <
notifications@github.com>:

**Comment by morphers82** [comment]
Well that worked using a post with the body being the --data part and the url being: https://mainnet.infura.io in postman
However, that in no way shows how to use the api endpoint with the get like it says is supposed be able to happen.  I tried the hex and true values in params in a GET like the api docs suggest with still no luck.

**Comment by comodoro** [comment]
I tried URL from [their generator](https://infura.docs.apiary.io/#reference/0/v1jsonrpcnetworkmethod/get?console=1) in Chrome and it seems to work:

`https://api.infura.io/v1/jsonrpc/mainnet/eth_getBlockByNumber?params=%5B%220x61a80%22%2Ctrue%5D`

returns something like

`{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x57a418a7c3e"...`

Haven't you forgotten to check the `params` checkbox? I did it too and the error message above appeared. A suggestion emerging from this github issue might be more intuitive error message.

**Comment by johanherman** [comment]
Hey @morphers82. Hope you got it to work eventually. Otherwise don't hesitate to contact us again.
