### ISSUE TITLE
Infura Kovan seems to be out of sync

### ISSUE THREAD

**Issue by wnz99** [INFURA/infura#48]
Hi,

I'm experiencing issues when getting an account balance with `eth_getBalance` from Infura Kovan endpoint. The call responds with an out of date balance. I also tried to pass the latest blocknumber as second parameter and got the following error:

`eth_getBalance(["0xc8dcd42e846466f2d2b89f3c54eba37bf738019b","0x4e8bc9"]): -32602: Unknown block number`

This behaviour appears only with recent blocks, so it seems to be due to some sync issue or delay in syncing.

I do no have this issues with a local node, or our own remote node, and identical js code.

Could you please confirm? This is something I've been noticing for at least the last two weeks.

MetaMask also seems to have similar issues. Please check the screenshot below. Etherscan shows the right balance, while MetaMask a balance of a couple of days before.

![i106 cimgpsh_orig](https://user-images.githubusercontent.com/12447140/34322886-ef659a06-e833-11e7-8601-1f78595bae20.png)

**Comment by tueric** [comment]
Hey @wnz99 seems like our Kovan nodes were out of sync. They should be a-ok now.

**Comment by ncocchiaro** [comment]
Still having issues @wnz99? Our Kovan nodes as well as the Kovan network authorities have been stable for some time now.

**Comment by wnz99** [comment]
@ncocchiaro yes, they seem to be stable now.

**Comment by ncocchiaro** [comment]
Cool, closing for now then.
