### ISSUE TITLE
Transactions occasionally dropped without reaching chain

### ISSUE THREAD

**Issue by danfinlay** [INFURA/infura#5]
Down at MetaMask, we've had some developers report that some transactions are not reaching the main chain.

Maybe Infura needs to retry txs until they're accepted? In any case, these devs need to know what the status of this issue is.

MetaMask/metamask-plugin#760
MetaMask/hello#34

Are two that I can find off the top of my head, but we've had several reports.  I'm opening this issue so those devs have a place they can go to track the progress.

**Comment by hermanjunge** [comment]
As today, OCT.31, we are in the middle of an architecture migration to `0.1.0`. We have also plans to build a transaction pool monitor as soon as this migration is ready. Will report in this very issue its progress.

**Comment by egalano** [comment]
Since July 2017, transactions submitted via Infura are cached in an off-chain index and periodically re-submitted to the network several times until successfully mined or properly rejected by the network. Additional upstream work by the client teams to avoid transactions being dropped from the local txpool in times of high congestion also helped resolve this issue.

**Comment by Alex1100** [comment]
I am still experiencing this issue today. 

```
const sendEth = async (req, res, next) => {
  try {
    if (req.privateKey) {
      const { toAddr, fromAddr, amount } = req.body;

      //ETHEREUM NETWORK IS TOO DAMN CONGESTED...
      //THE GAS PRICES ARE ALMOST ALWAYS NOT ENOUGH
      //FOR THE NETWORK TO RECOGNIZE THE TRANSACTION
      //I AM SENDING 0.02+ ETH AT A TIME, AND STILL
      //NO DICE

      const currentBalance = await web3.eth.getBalance(fromAddr);
      const currentGasPrice = await web3.eth.getGasPrice();

      const rawTx = {
        nonce: a,
        from: fromAddr,
        to: toAddr,
        gas: web3.utils.toHex(21000),
        gasLimit: web3.utils.toHex(1500000000),
        gasPrice: web3.utils.toHex(100000000000),
        value: web3.utils.toHex(web3.utils.toWei(amount, 'ether')),
        data: ""
      };

      const fromAddrPKey = req.privateKey.slice(2, req.privateKey.length);
      let fromAddrPKeyX = new Buffer(fromAddrPKey, 'hex');

      const tx = new EthTx(rawTx);
      tx.sign(fromAddrPKeyX);

      let serializedTx = `0x${tx.serialize().toString('hex')}`;

      eth.sendRawTransaction(serializedTx)
        .then(successTxHash => {
          console.log("Success Tx Hash Is: ", successTxHash);
          res.status(200).json({transactionChecker: `https://etherscan.io/tx/${successTxHash}`, serializedTx, successTxHash, from: fromAddr, to: toAddr})
        })
    } else {
      throw new Error("PAYMENT DIDN'T GO THROUGH");
    }
  } catch (e) {
    console.log("PAYMENT DIDN'T GO THROUGH: ", e.message);
    return res.status(422).send(e.message);
  }
};
```

results in ```{
  "transactionChecker": "https://etherscan.io/tx/0x9d396a89f80c477b817c8ea76451a34a730dd27437d93973da0f78a5d23c48cf",
  "serializedTx": "0xf8718689ec9023a45485174876e8008252089409a6737516ba5cdf9f4fe397bc31308a7623a2cc876a94d74f430000801ba025a8a3ab1ba53013ce6c9de0cd9ad19bcd66bfc9819d5e86a127809f6859de90a00f7ae8ebc54e3e2967c98152c3a613bb47ff83adb4e17aa39929f01907b1ac23",
  "successTxHash": "0x9d396a89f80c477b817c8ea76451a34a730dd27437d93973da0f78a5d23c48cf",
  "from": "0x406bef20E388065482CAC8E240987B7d8e194B14",
  "to": "0x09a6737516Ba5cdf9f4FE397Bc31308a7623A2cc"
}```

yet when I check the etherscan.io link it say no transaction has been found.
