### ISSUE TITLE
Infura is missing events sometimes

### ISSUE THREAD

**Issue by olaf89** [INFURA/infura#50]
With the same get_logs parameters, different number of events is returned. FromBlock and ToBlock are constant and are in the past. I tested is also agains etherscan API which always returns same result.

Here is reproduced:
https://stackblitz.com/edit/angular-2aowai?file=app%2Fapp.component.ts

**Comment by tueric** [comment]
Gunna close this since its a duplicate of #51. Future updates will be there.
