### ISSUE TITLE
eth_estimategas timeout

### ISSUE THREAD

**Issue by guptapriyank** [INFURA/infura#52]
we are trying to estimate the raw transaction, but getting a timeout exception. Timeout problem can be seen if you select INFURA network in myetherwallet, to send all your Ether or any other type of estimation.

**Comment by tueric** [comment]
Hey @guptapriyank. The `eth_estimateGas` method as handled by geth is quite inefficient. We're working on a more efficient implementation right now.

**Comment by guptapriyank** [comment]
Thanks, @tueric, I am waiting for it desperately.

**Comment by nirmalgupta** [comment]
me too.

**Comment by ryanschneider** [comment]
This new implementation has just been released on mainnet for all customers, if anyone is still seeing issues on mainnet please at-reply me.

**Comment by ryanschneider** [comment]
@nirmalgupta do you have the POST body as well?

**Comment by nirmalgupta** [comment]
Payload:
```
{"jsonrpc":"2.0","id":5,"method":"eth_estimateGas","params":[{"data":"0x095ea7b30000000000000000000000005ad853e89ae538a937951d1b43de1046d8536071000000000000000000000000000000000000000000000000000000174876e800","to":"0x0f4ca92660efad97a9a70cb0fe969c755439772c"}]}
```
Request Header
```
:authority:mainnet.infura.io
:method:POST
:path:/5Ik2NwtzUQsXpL5nAvXW
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.9
content-length:262
content-type:application/json
dnt:1
origin:https://stake.leverj.io
referer:https://stake.leverj.io/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```

**Comment by ryanschneider** [comment]
We hadn't patched the route that handles batched RPC methods internally, but just did, is it possible you were sending something more like `[{"jsonrpc":"2.0","id":5,"method":"eth_estimateGas","params":[{"data":"0x095ea7b30000000000000000000000005ad853e89ae538a937951d1b43de1046d8536071000000000000000000000000000000000000000000000000000000174876e800","to":"0x0f4ca92660efad97a9a70cb0fe969c755439772c"}]}]` (note the enclosing array) ? 

@nirmalgupta Can you give it another try to see if that change fixed it for you?

**Comment by nirmalgupta** [comment]
issue has resolved for me after i put `from:userAddress`  in params. Thanks for your help.

**Comment by ryanschneider** [comment]
Glad to hear it, @nirmalgupta.  @guptapriyank I'm closing this issue since I believe it's resolved w/ our recent changes, but if you still see any issues please at-reply me.
