### ISSUE TITLE
eth_sendRawTransaction returns tx's hash but doesn't get onto blockchain

### ISSUE THREAD

**Issue by tinbka** [INFURA/infura#53]
Maybe this is not a specific Infura problem but...

I use https://github.com/se3000/ruby-eth to sign transactions, I tested it yesterday on Ropsten https://ropsten.infura.io and it worked just fine.
Now I'm trying to send signed transactions via mainnet.infura.io the same way to the mainnet. It looks like this:

This is the address I'm trying to work with https://etherscan.io/address/0x5c70685d40e5f5560189e07213d74c240b276c85
```ruby
# Check my address balance, 1 ETH in accordance with etherscan.io
client.get_balance "0x5C70685d40E5F5560189E07213D74c240b276C85"
# => 1000000000000000000

# Get the private key from the database
key = Eth::Key.new priv: source_private_hex

# Set the content, here I take explicitly high price and volume of gas
args = { 
      from: "0x5C70685d40E5F5560189E07213D74c240b276C85", # key.address
      to: "0xee4946273319B322CFdBB8B444A6808b024d4f50",
      value: 996000000000000000, # the address balance minus gas
      data: "",
      nonce: 1000, 
      gas_limit: 200000,
      gas_price: 20000000000
}

# Create and sign a new transaction
tx = Eth::Tx.new(args)
tx.sign key

tx.hex
# => "0xf86f8203e88504a817c80083030d4094ee4946273319b322cfdbb8b444a6808b024d4f50880dd280b9144a00008026a0664b11211bba572a57808c8825681cdd14a90df878a3bd72539af7e40555ad8ba04e69af4be4fce733f5e47179aaf3eb04b457f7c9bf5607052d43919205d4858c"

# Call curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_sendRawTransaction", "params": [<tx.hash>]}' "https://mainnet.infura.io/myapitoken"
client.eth_send_raw_transaction(tx.hex)
# => {"jsonrpc"=>"2.0","id"=>1,"result"=>"0x1453e086a8a1f0e9ac9fa4fe1685f7c42928525ecf9c5ee4b7d22972508950ab"}

# Yet the balance is the same from the point of view of the same node
client.get_balance "0x5C70685d40E5F5560189E07213D74c240b276C85"
# => 1000000000000000000
```

As you can see there is no outgoing transactions from https://etherscan.io/address/0x5c70685d40e5f5560189e07213d74c240b276c85

From here, I can't localize the problem. Is there any option to debug the transaction?

**Comment by tueric** [comment]
Hi @tinbka. It seems like your nonce value is way off. Generally you can't just use any nonce. I suggest you getTransactionCount before you send a transaction. That function will return your current account nonce.

**Comment by tinbka** [comment]
Hi @tueric, thanks for that fast reply. I've tried to use the result of getTransactionCount first. So the count was always 0 and it haven't been sitting either. 
Then I read on the Stackexchange that nonce must take into account the transactions that are still in the txpool, and I can't say for sure how many of them are there. So I put a relatively large number into nonce (with no help).

**Comment by tinbka** [comment]
Well, increasing gas price up to 5 GWei seems to help. Maybe it's just TX TTL that is set quite low and my txes with 1 GWei gas price were eliminated before someone mined them.
