### ISSUE TITLE
Read Events from Blockchain using Infura.io instead of parity

### ISSUE THREAD

**Issue by mohube** [INFURA/infura#56]
I have a Script that is reading events from the Ethereum blockchain and want to use infura.io instead of my full parity client. Unfortunately I get the following error as soon as I change the 127.0.0.1:8545 in this code to my Infura.io Access link.

```
 var fs = require("fs");
var Web3 = require('web3');

var web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider('http://127.0.0.1:8545'));
```

```
Error: Invalid JSON RPC response: ""
at Object.InvalidResponse (/Users/moritzhubel/node_modules/web3/lib/web3/errors.js:38:16)
at XMLHttpRequest.request.onreadystatechange (/Users/moritzhubel/node_modules/web3/lib/web3/httpprovider.js:116:24)
at XMLHttpRequestEventTarget.dispatchEvent (/Users/moritzhubel/node_modules/xhr2/lib/xhr2.js:64:18)
at XMLHttpRequest._setReadyState (/Users/moritzhubel/node_modules/xhr2/lib/xhr2.js:354:12)
at XMLHttpRequest._onHttpRequestError (/Users/moritzhubel/node_modules/xhr2/lib/xhr2.js:544:12)
at ClientRequest.<anonymous> (/Users/moritzhubel/node_modules/xhr2/lib/xhr2.js:414:24)
at emitOne (events.js:116:13)
at ClientRequest.emit (events.js:211:7)
at Socket.socketErrorListener (_http_client.js:387:9)
at emitOne (events.js:116:13)
```
Is there anyone who can help?

**Comment by tueric** [comment]
Which url are you using for Infura? Could you post that without your API token?

**Comment by mohube** [comment]
I am using https://kovan.infura.io/

**Comment by tueric** [comment]
Cool. A lot of the times people put http instead of https... 
Which request/method is it failing on?

**Comment by mohube** [comment]
It is failing with https. I tried it with http, but in that case just nothing happens. But the script works without any problem using my parity node via localhost.

**Comment by tueric** [comment]
Yes, I understand. What im asking is what method is fails on e.g. `getBalance`, `sendRawTransaction`, etc...

**Comment by mohube** [comment]
var fs = require("fs");
var Web3 = require('web3');

var web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider('http://kovan.infura.io/'));

var instance = web3.eth.contract();
var mycontract = instance.at();

var events = mycontract.event({}, {fromBlock: '0', toBlock: 'latest'});
events.watch(function(error,event) {

so I cut this snippet out of the code so these are basically all the methods I am using

**Comment by tueric** [comment]
I see. So the issue, is that Infura currently doesn't support Events due to the stateful nature of the call. If you really need events, you can try https://pkovan.infura.io.

**Comment by mohube** [comment]
Oh it is working thank you! But is it stable to use it?

**Comment by tueric** [comment]
If you want stability, I suggest you use Rinkeby instead. I've seen higher rates of stability on the Rinkeby testnet. Also, we have some websocket endpoints on Rinkeby as well, and that should be more efficient on the client side.

**Comment by mohube** [comment]
Alright, thank you very much! I'm going to use Rinkeby instead now

**Comment by vijaytabhatt** [comment]
@tueric  are events supported by infura ?
if yes . do we need http provider or websocket provider ? we are currently using rinkeby and then wish to move to mainnet
