### ISSUE TITLE
Sign up page error

### ISSUE THREAD

**Issue by nasht00** [INFURA/infura#64]
When clicking on submit on your sign up form, the form iframe becomes a blank box.

Network traffic shows a 500 Internal server error. I get no email confirmation.

Trying to sign up again says the address is already used. I've already burned 3 of my email addresses trying to sign up, to no avail ...

**Comment by d0o0** [comment]
i also meet the same problem.

**Comment by katastreet** [comment]
same here not even getting any emails and the email address  is unusable now

**Comment by richburdon** [comment]
Same thing. The link in the internal iframe is broken.

**Comment by nick** [comment]
The web developer console shows a number of error messages and it seems there is some recurring `console.log('hi')` happening somewhere...

**Comment by codedplanetuk** [comment]
I have the same problem. I have tried 4 email addresses now. The page just errors and it doesn't send email. It will not let you re-try with the same email once it fails (as it says the email already exists).

![image](https://user-images.githubusercontent.com/1923400/35407404-c24ce382-0203-11e8-8bd6-2dba74742385.png)

**Comment by wuehler** [comment]
Apologies, we are receiving hundreds of registrations a day and seeing mail being delivered on it as well. In the mean time, please just email infura@infura.io and we will reply with your access key.

**Comment by mbgodsey** [comment]
Checking in, are you still seeing this issue?

**Comment by tueric** [comment]
Closing because no reply. Looks like its been fixed as well.

**Comment by shessenauer** [comment]
This is still an issue, unable to just 'sign in' without going through several emails.

**Comment by khoan** [comment]
What's the current on boarding process?

Upon submit on `https://infura.io/register` got js error: `Failed to load resource: the server responded with a status of 401 () https://infura.io/api/user/register`
