### ISSUE TITLE
Infura Kovan gas estimate transaction error

### ISSUE THREAD

**Issue by wnz99** [INFURA/infura#66]
Are you aware of any issues with RPC call eth_estimateGas on your Kovan endpoint?

We are using MetaMask in our dapp and since a few weeks gas estimate calls return a transaction error on Infura Kovan.

The above does not happen if we set our own server as a custom endpoint in MetaMask. Therefore it has to be some issue with either MetaMask or Infura Kovan endpoint.

Could you please check?

**Comment by tueric** [comment]
Hey @wnz99! Can you give some more details on what the error was? You mentioned estimateGas, but then you said you got a transaction error. So did the error come from the estimateGas call or some transaction call? Some more info such as the request body or the response would be great

**Comment by sulliwane** [comment]
you may have forgot to add the ```value: web3.toHex(value)``` parameter to the object input of web3.eth.estimateGas function...you need it if the function called in the contract is payable (note: this is specific to Parity, Geth will not check the value when estimating the transaction cost)

**Comment by wnz99** [comment]
@tueric the error simply disappeared. It must have something to do with your nodes instability, since it appeared suddenly and I could not replicate it on our Parity nodes.

**Comment by ncocchiaro** [comment]
There have been issues recently with the Kovan authorities as well as with the ability of clients to sync up the chain (you can see references to this in the Parity release notes as well). After we upgraded our nodes to Parity 1.8.7+ things have improved, if this issue no longer occurs I'm closing it for now.
