### ISSUE TITLE
post eth_blockNumber returns nothing

### ISSUE THREAD

**Issue by Leoatstentor** [INFURA/infura#67]
I am trying the tutorial [https://blog.infura.io/getting-started-with-infura-28e41844cc89](url)
The eth_blockNumber method call returns nothing.

`C:\WINDOWS\system32>curl -X POST --data '{"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}' https://mainnet.infura.io/jOfeAdgUsr1l2uwZKcYc

C:\WINDOWS\system32>curl -X POST --data '{"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}' https://ropsten.infura.io/jOfeAdgUsr1l2uwZKcYc

`

**Comment by tueric** [comment]
Hi @Leoatstentor. How are you running curl on your Windows machine? Are you using the Linux subsystem?

**Comment by Leoatstentor** [comment]
Thanks Eric. Per your reminding, I tried it in ubunto in WSL, it returns
result
{"jsonrpc":"2.0","id":1,"result":"0x4c849a"}

But nothing with windows 10 cmd.exe as administrator.
Nothing from js in a webpage run by http-server in windows 10 either.

**Comment by johanherman** [comment]
Hi @Leoatstentor. As far as I know in some versions of Windows the default `curl` command will be an alias to some PowerShell command. Ie it will not work as you would expect. You can download a Windows binary from https://curl.haxx.se/download.html (although I'm not sure how well it works in all situations), or run the Linux version, which seemed to work fine for you. 

Regarding your other issue with your JS webpage not working: you'll have to be more specific than that for us to be able to give you some pointers. Most likely the framework or library you're using should have some API documentation that you should be able to use transparently for this use case. Just replace their references for the RPC node with our address and your token.

**Comment by Leoatstentor** [comment]
Thanks Johan.
