### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by jmiglietta-proxy** [INFURA/infura#68]
We have a service that uses your api.  It had been running fine for a few days, until this crash (below).  Any ideas on what would cause that?  We are calling: 

InfuraApi.prototype.getBlockByNumber = function(blockNumber, includeTransactions) {
        if(includeTransactions === undefined) includeTransactions = true
        const apiCall = `https://api.infura.io/v1/jsonrpc/${this.network}/eth_getBlockByNumber?params=["0x${blockNumber.toString(16)}",${includeTransactions}]`
		return restCall(apiCall)	
    }

C:\inetpub\nodejs\node_modules\solc\soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&file

**Error: getaddrinfo ENOTFOUND api.infura.io api.infura.io:443**
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

**Comment by johanherman** [comment]
Hello @jmiglietta-proxy. `getaddrinfo ENOTFOUND` is (as you can interfere by the stacktrace) typically thrown when you can't resolve the hostname. It is hard to tell exactly what went from in this situation, but some of your upstream DNS providers could e.g. have been experiencing temporary problems. I understand that Nodejs can also throw this in other situations such as e.g. incorrectly made function calls. Or you might be hitting local resource limits if you're trying to resolve the address in a large amount of concurrent calls.
