### ISSUE TITLE
Error using Infura as web3 provider Error 405

### ISSUE THREAD

**Issue by asghaier76** [INFURA/infura#72]
I am using Infura as the web3 provider however sending a transaction will return this error

Failed to load resource: the server responded with a status of 405 (HTTP/2.0 405)
Error: Invalid JSON RPC response: ""

**Comment by tueric** [comment]
Can you give more information, such as what RPC method causes the 405 error? A code snippet would help.

**Comment by asghaier76** [comment]
Hi Eric

So this is done in Ionic using Angular to make things clear, as I run this
in the browser with MetaMask it works but once I run it without MetaMask I
start to see this

Here is a snippet

if (typeof web3 !== 'undefined') {
    web3 = new Web3(web3.currentProvider);
  } else {
    // set the provider you want from Web3.providers
    web3 = new Web3(new Web3.providers.HttpProvider("
https://ropsten.infura.io/TOKEN"));
  }


$scope.createDID = function(){


      contract = web3.eth.contract(ABI);

      contractInst = contract.at(CONTRACRTADDR);
      console.log(contractInst);
      console.log(web3.eth.defaultAccount);

      contractInst.create('12345','67890','123',{from: SENDERADDRESS} ,
function(error, result){
        //$ionicLoading.show({template: '<p>Please
wait...</p><ion-spinner></ion-spinner>'});
        alert("launchign create DID");
        if(!error){
            $scope.txhash = result;
            console.log("res"+result);
            alert("Your DID is being generated, wait for few minutes and
then hit proceed.");

        }else{
            console.log(error);
            alert(error);
        }

      })
    }

**Comment by tueric** [comment]
I see. The reason this is happening is because if you don't use MetaMask, you don't have an account to deploy from. `web3.eth.defaultAccount` will not return to you an account. This is because Infura does not store your keys... So when you try to get your account and then try to make a transaction, it will not work.

**Comment by asghaier76** [comment]
Hi

I have already set the default account using

  $rootScope.web3.eth.defaultAccount = DEFAULT_ACCOUNT;

But I suspect that since I am not signing any transaction that could be the
case. If so, how can I from the app call the contract function

Ahmad

**Comment by tueric** [comment]
Yeah. You will need to sign your own transactions. You can sign using https://github.com/ethereumjs/ethereumjs-tx.
