### ISSUE TITLE
Unexpected 0 returned 

### ISSUE THREAD

**Issue by wangzhen10** [INFURA/infura#79]
I have a contract method which should return a not 0 number. But recently, it always returns 0x0000000000000000000000000000000000000000000000000000000000000000. Does anyone have any idea why this happens? Any comments will be appreciated!

**Comment by tueric** [comment]
Hey @wangzhen10.
Can I get what RPC methods you are calling? More specifically, the payload would be good.

**Comment by tueric** [comment]
Gunna close this issue due to lack of reply. Please comment here and "@" me if there are any other issues.
