### ISSUE TITLE
IPFS No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by zerostatic** [INFURA/infura#81]
I'm getting error: Failed to load https://ipfs.infura.io:5001/api/v0/add?pin=true: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin

This has been working fine in the past

**Comment by moskalyk** [comment]
Is the public Infura IPFS node down?

**Comment by zerostatic** [comment]
It seems to be working fine again

**Comment by ncocchiaro** [comment]
We had issues with our IPFS gateway today that may have manifested in this way (and others). We believe them to be resolved and are monitoring our service, however we can reopen this issue if the problem happens again.
