### ISSUE TITLE
JSON-RPC calls return invalid JSON

### ISSUE THREAD

**Issue by turbolent** [INFURA/infura#82]
Some JSON-RPC method calls randomly return invalid JSON. The server responds with status code 200, `Content-Type: application/json`, but the body is just `invalid host specified`. For example, using HTTPie:

```
$ echo '{"jsonrpc": "2.0", "id": 1, "method": "eth_getBalance", "params": ["0xab7E97c3f00d23eD3d0B15BAD55539F1163A1bE8", "latest"]}' | http post https://mainnet.infura.io/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 23
Content-Type: application/json
Date: Fri, 23 Feb 2018 23:42:01 GMT
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin

invalid host specified
```

This happens about 1 out of 10 times.

**Comment by egalano** [comment]
This was an error that we encountered with version 1.8.x of geth being rolled out. It should have been resolved within our system. We'll take a look at this immediately

**Comment by ncocchiaro** [comment]
This should now be fully resolved, let us know if you see it again.
