### ISSUE TITLE
Using promises with web3 with Infura

### ISSUE THREAD

**Issue by elie222** [INFURA/infura#84]
I switch between using local Geth and Infura. With Geth web3 promise style works fine. With Infura it doesn't work.

How can I get my code to be compatible with both?

**Comment by tueric** [comment]
Hey @elie222, can I have a look at what you are trying to do? We don't have the ability to enforce whether you use promises or not... A code snippet might allow me to help you fix things.

**Comment by jmiglietta-proxy** [comment]
Write a wrapper

**Comment by elie222** [comment]
Hi, thanks. So we did end up using wrappers. We were already in most
places, but in some we weren't which caused the issue.

**Comment by tueric** [comment]
Awesome! Sounds like you fixed it. Was the issue that you tried to use promises in Web3? AFAIK, they dont have promises in pre-Web3 1.0. They do have promises in Web3 1.0 though.

**Comment by elie222** [comment]
I don't remember exactly now but I think we were doing get accounts as a
promise with web3 1.0 and then tried to do the same with pre 1.0 which
didn't work.

I don't fully understand why switching provider causes these changes.
Surely it only matters to our own client if we use promises or not and that
shouldn't have changed whether I was connecting to  local geth node or
infura?

In any case we got it all working consistently now using a promisify
function.

Thanks for the help

**Comment by tueric** [comment]
Yeah. Whether you use promises or not should not concern Infura at all. 
Anyways, glad you figured it out! Closing issue.
