### ISSUE TITLE
Probabilistic SyntaxError in eth_getLogs

### ISSUE THREAD

**Issue by wjmelements** [INFURA/infura#85]
Occasionally, I see this error in the logs.
```
Error: Error: [ethjs-rpc] rpc error with payload {"id":9627017936709,"jsonrpc":"2.0","params":[{"to":"pending","fromBlock":"0x1bd71e","toBlock":"0x1c0729","address":"0xc8f6dad178adcf44aacc79d8658960e18acbba03","topics":["0xb026a0d6eb8b5919e909850a1d0ab0f3468e08b48ef884a544e886fb93d6ab04"]}],"method":"eth_getLogs"} Error: InfuraProvider - cannot complete request. All retries exhausted.
Original Error:
SyntaxError: Unexpected token i in JSON at position 0
```

**Comment by egalano** [comment]
Which network is this against?

**Comment by wjmelements** [comment]
Rinkeby

**Comment by egalano** [comment]
I’m actually in the process of fixing this error on rinkeby this is related to #83 it should be resolved in a couple of hours once the update is pushed and I’ll notify you on this ticket. Thanks for your patience.

**Comment by egalano** [comment]
The update was rolled out earlier today, tested and verified. Please open a new issue if you encounter any errors. Thanks.

**Comment by wjmelements** [comment]
I haven't seen this issue since the update.
