### ISSUE TITLE
403 error on "ipfs pin ls" command

### ISSUE THREAD

**Issue by benjohnson2001** [INFURA/infura#86]
I'm trying to see the pinned hashes of the node, but I don't seem to have permissions. Is this expected behavior?

```
$ curl "https://ipfs.infura.io:5001/api/v0/pin/ls" -vvv
*   Trying 34.192.181.130...
* TCP_NODELAY set
* Connected to ipfs.infura.io (34.192.181.130) port 5001 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: ipfs.infura.io
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /api/v0/pin/ls HTTP/1.1
> Host: ipfs.infura.io:5001
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Server: nginx/1.10.3 (Ubuntu)
< Date: Mon, 26 Feb 2018 21:56:25 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< 
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host ipfs.infura.io left intact

**Comment by ncocchiaro** [comment]
We don't allow certain portions of the API on the gateway for security reasons, though we're in the process of revamping that setup. Do you have a particular use case that requires listing the pinned hashes?

**Comment by benjohnson2001** [comment]
I wanted to see if I could use the Infura IPFS node instead of hosting my own, based on https://github.com/INFURA/infura/issues/15 it looked like I could. Although I guess if that were true then anyone could just "ipfs pin rm" them so maybe I would be better off running my own.

**Comment by ncocchiaro** [comment]
We're working on a user-based authenticated service where you'll have more control over the items you pin to local storage and you'll be able to list and remove them, avoiding the danger of just anyone doing it. This is unfortunately not yet available, but we'll send out an update on all our communication channels as soon as it is.

**Comment by ebadiere** [comment]
Is there an update on this?  I tried to rm a pinned hash through infura today and was not able to.  I was able to do it using my local daemon.

**Comment by ncocchiaro** [comment]
No update yet. This is a work in progress but it will take some time to fully complete development and roll it out to production. For the moment we're still disallowing pin removal for the reasons outlined above.
