### ISSUE TITLE
Support for new Ropsten Testnet

### ISSUE THREAD

**Issue by ice09** [INFURA/infura#9]
Might be a little early, but it'd be great to have Ropsten support from the beginning, could be another good argument for using infura without having to install/setup new Testnet clients locally.

https://blog.ethereum.org/2016/11/20/from-morden-to-ropsten/

**Comment by hermanjunge** [comment]
Thanks for the input @ice09 (and love the Vonnegut's Cat's Cradle reference... Or is the Satriani's Song?)

We are already making the calculations in terms of hardware in order to start giving support to the `ropsten` network. Stay tuned.

**Comment by egalano** [comment]
Infura support for Ropsten is now live at:
https://ropsten.infura.io as well as
https://testnet.infura.io

Currently running both geth 1.5.2 and parity 1.4.4 within the cluster.

**Comment by jtakalai** [comment]
JFYI: on your "Hello X!" page, it still says "Test Ethereum Network (Morden)" even though the URL is  ropsten.infura.io

Maybe update UI strings?  (:

**Comment by hermanjunge** [comment]
@wuehler ^^

**Comment by wuehler** [comment]
Thanks, fixed.
