### ISSUE TITLE
WebSocket Origin Header

### ISSUE THREAD

**Issue by asymmetric** [INFURA/infura#90]
Hi,

I'm trying to access the WebSocket endpoint using geth's [rpc package](https://github.com/ethereum/go-ethereum/tree/master/rpc), but the subscription call stalls indefinitely.

Is the `Origin` header validated in any way, similar to [Parity](https://wiki.parity.io/Configuring-Parity)'s `chrome-extension://*`check?

**Comment by ryanschneider** [comment]
No, we do not limit access based on the `Origin` header.  Can you post some code snippets so we can see exactly how you're using the rpc package to connect?  Have you tried other RPCs than subscriptions, I'd like to confirm that it's actually getting past the `Dial` stage.

**Comment by asymmetric** [comment]
It turns out that [this](https://github.com/ethereum/go-ethereum/issues/16299) was the problem: I was making calls using `newBlocks`, which seems to have been deprecated in favour of `newHeads`.

**Comment by egalano** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define a policy and implement a process for cleaning up IPFS snapshots](https://trello.com/c/VTfv2dVH/32-define-a-policy-and-implement-a-process-for-cleaning-up-ipfs-snapshots)
