### ISSUE TITLE
Web3 connecting INFURA failes for Parity methods

### ISSUE THREAD

**Issue by Derek-yfqiu** [INFURA/infura#91]
Currently I have an issue in connecting INFURA to the Web3.js that uses Parity methods. My idea is to use INFURA as client node for a ETH explorer https://github.com/gobitfly/etherchain-light, in order to avoid downloading many GB of chain data through Parity. What I did is to assign INFURA as provider to web3 as follow:
provider = web3.providers.HttpProviders("https://mainnet.infura.io/MYTOKEN")

The etherchain-light explorer are partially work in accessing data like "recent block" and "recent transaction". But when I try to access more detail information inside the transaction using method "web3.parity.pendingTransactions, "web3.trace.transaction" then errors are return and report "Invalid JSON RPC response".

I notice that GETH is the default client that INFURA is used. There is a way in changing preferred client with "-H "Infura-Ethereum-Preferred-Client: parity" using curl. But I don't know if there any way to set this preference with web3. 

Thanks for any hints about this!

**Comment by tueric** [comment]
That header is not in use anymore. Sorry for the confusion. We will update the docs to reflect that. We currently do not support those parity specific methods.

**Comment by Derek-yfqiu** [comment]
Thanks for the reply! It is a pity that Parity is not supported any more. I would be very interested to know whether there are some more activity regarding parity.

**Comment by tueric** [comment]
We do support Parity. For example we have parity running on Kovan. 
We just don't support those parity specific methods just like how we don't support the debug api on geth. We are actively doing research on ways we can support those calls in a scalable and reliable way.
